name: Custom Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: custom_test-${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}

jobs:
  float8-test:
    runs-on: amz2023.linux.g6.4xlarge.experimental.nvidia.gpu
    steps:
      - name: Checkout code
        run: |
          conda create -n venv python=3.9 -y
          conda activate venv
          echo "::group::Install newer objcopy that supports --set-section-alignment"
          yum install -y  devtoolset-10-binutils
          export PATH=/opt/rh/devtoolset-10/root/usr/bin/:$PATH
          python -m pip install --upgrade pip
          pip install ${{ matrix.torch-spec }}
          pip install -r dev-requirements.txt
          pip install .
          pytest test/float8 --verbose -s
