name: Run Regression Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: 4-core-ubuntu-gpu-t4
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        pip install torch
        

    - name: Install package
      run: |
        pip install .

    - name: Run tests
      run: |
        pytest test --verbose -s -x

  test-nightly:
    runs-on: 4-core-ubuntu-gpu-t4
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cu121
        

    - name: Install package
      run: |
        pip install .

    - name: Run tests
      run: |
        pytest test --verbose -s -x

  test-cpu:
    runs-on: 32-core-ubuntu
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        pip install torch --index-url https://download.pytorch.org/whl/cpu
        

    - name: Install package
      run: |
        pip install .

    - name: Run tests
      run: |
        pytest test --verbose -s -x

  test-nightly-cpu:
    runs-on: 32-core-ubuntu
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu
        

    - name: Install package
      run: |
        pip install .

    - name: Run tests
      run: |
        pytest test --verbose -s -x
