name: Run Regression Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: regression_test-${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: CUDA 2.2.2
            runner: linux.g5.12xlarge.nvidia.gpu
            torch_spec: 'torch==2.2.2'
            marker: ""
          - name: CUDA 2.3
            runner: linux.g5.12xlarge.nvidia.gpu
            torch_spec: 'torch==2.3.0'
            marker: ""
          - name: CPU 2.2.2
            runner: linux.4xlarge
            torch_spec: 'torch==2.2.2 --index-url https://download.pytorch.org/whl/cpu'
            marker: ""
          - name: CPU 2.3
            runner: linux.4xlarge
            torch_spec: 'torch==2.3.0 --index-url https://download.pytorch.org/whl/cpu'
            marker: ""
          - name: CPU Nightly
            runner: linux.4xlarge
            torch_spec: '--pre torch==2.5.0.dev20240709+cpu --index-url https://download.pytorch.org/whl/nightly/cpu'
            marker: ""
          - name: CUDA Nightly Part 1
            runner: linux.g5.12xlarge.nvidia.gpu
            torch_spec: '--pre torch==2.5.0.dev20240709+cu121 --index-url https://download.pytorch.org/whl/nightly/cu121'
            marker: "group1"
          - name: CUDA Nightly Part 2
            runner: linux.g5.12xlarge.nvidia.gpu
            torch_spec: '--pre torch==2.5.0.dev20240709+cu121 --index-url https://download.pytorch.org/whl/nightly/cu121'
            marker: "group2"

    uses: ./.github/workflows/reusable_test.yml
    with:
      runner: ${{ matrix.runner }}
      torch_spec: ${{ matrix.torch_spec }}
      marker: ${{ matrix.marker }}
